# Generated by Django 5.1.4 on 2024-12-26 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidasAero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(blank=True, max_length=6, null=True, verbose_name='ORG')),
                ('matricula', models.IntegerField(max_length=13, verbose_name='MATRICULA')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='NOME')),
                ('un_org', models.CharField(blank=True, max_length=50, null=True, verbose_name='UND. ORGANIZACIONAL')),
                ('cargo', models.CharField(blank=True, max_length=20, null=True, verbose_name='CARGO')),
                ('ind_parcs_pg', models.CharField(blank=True, max_length=20, null=True, verbose_name='INDICE DE PARCELAS PAGAS')),
                ('valor', models.BooleanField(blank=True, max_length=20, null=True, verbose_name='VALOR')),
                ('caixas', models.CharField(blank=True, max_length=120, null=True, verbose_name='CAIXAS')),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='aero.cadastros', verbose_name='CADASTRO')),
            ],
        ),
    ]
