# Generated by Django 5.1.4 on 2024-12-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saidasaero',
            name='matricula',
            field=models.IntegerField(verbose_name='MATRICULA'),
        ),
    ]
