# Generated by Django 5.1.4 on 2024-12-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(blank=True, null=True, unique=True, verbose_name='MATRÍCULA')),
                ('nome_pessoa', models.CharField(blank=True, max_length=100, null=True, verbose_name='NOME PESSOA')),
                ('posto', models.CharField(blank=True, max_length=50, null=True, verbose_name='POSTO')),
                ('sigla_uo', models.CharField(blank=True, max_length=20, null=True, verbose_name='SIGLA UO')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='DATA ADMISSÃO')),
                ('data_termino', models.DateField(blank=True, null=True, verbose_name='DATA TÉRMINO')),
                ('cpf_pessoa', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF PESSOA')),
                ('banco', models.CharField(blank=True, max_length=50, null=True, verbose_name='BANCO')),
                ('agencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='AGÊNCIA')),
                ('tipo_conta', models.CharField(blank=True, max_length=20, null=True, verbose_name='TIPO CONTA')),
                ('numero_conta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº CONTA')),
                ('proventos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PROVENTOS')),
                ('descontos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DESCONTOS')),
                ('liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='LÍQUIDO')),
            ],
        ),
    ]
