# Generated by Django 5.1.4 on 2024-12-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastros',
            name='matricula',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='MATRÍCULA'),
        ),
    ]
